// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// signCurrent
CharacterVector signCurrent(NumericVector x);
RcppExport SEXP arbintools_signCurrent(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    __result = Rcpp::wrap(signCurrent(x));
    return __result;
END_RCPP
}
// assignRest
NumericVector assignRest(CharacterVector x);
RcppExport SEXP arbintools_assignRest(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    __result = Rcpp::wrap(assignRest(x));
    return __result;
END_RCPP
}
