# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' signCurrent
#'
#' Takes a vector of current values from a data frame of raw data, and assigns a letter
#' ("D", for discharging, "C", for charging or "R" for resting) based on the sign of the current.
#' This function is called as part of the arbin_process_Rmap function.
#' @param x The vector of current values to be processed
#' @export
#' @examples
#' raw$state <- signCurrent(raw$I)
signCurrent <- function(x) {
    .Call('signCurrent', PACKAGE = 'arbintools', x)
}

#' assignRest
#'
#' Takes a vector of character values outputted by the signCurrent function and assigns a unique
#' identifier for each distinct current-rest cycle. Called as part of the arbin_process_Rmap function.
#'
#' @param x The vector outputted by signCurrent to be processed.
#' @export
#' @examples
#' raw$rests <- assignRest(raw$state)
assignRest <- function(x) {
    .Call('assignRest', PACKAGE = 'arbintools', x)
}

